[package]
name = "Darbitex"
version = "4.0.0"
upgrade_policy = "immutable"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[addresses]
darbitex = "_"
